# -*- coding: utf-8 -*-
"""activations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJUZvbNZLvldb8-gl309goyz914mlIdg
"""

import numpy as np

"""Here, a library of functions to call in neural net code"""

def relu(inp):
  return np.log(1+np.exp(inp))

def tanh(inp):
  return 0.5+ 0.5*np.tanh(0.5*inp)

def sigmoid(inp):
  return 1/(1+np.exp(-inp))

x = [1,2,3]

relu(x)